language: cpp
compiler:
    - gcc
    - clang
# Change this to your needs
before_install:
    - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
      #    - sudo add-apt-repository --yes ppa:andykimpe/cmake3
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-5 g++-5
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
    # Install required cmake
    - sudo apt-get remove cmake
    - wget http://www.cmake.org/files/v3.2/cmake-3.2.1.tar.gz
    - tar -xzf cmake-3.2.1.tar.gz
    - cd cmake-3.2.1
    - ./bootstrap > /dev/null
    - make -j8 > /dev/null
    - sudo make install
    - cd ..
    - rm -rf cmake-3.2.1 cmake-3.2.1.tar.gz
script:
    - mkdir build && cd build && cmake ../ -DINTERNAL_LIBS=1 -DENABLE_TESTS=1 -DENABLE_DEMOS=0 && make
